# Generated by Django 4.1.2 on 2022-11-12 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Age', models.CharField(max_length=20)),
                ('Phoneno', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=20)),
                ('Addres', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=20)),
                ('Qualifications', models.CharField(max_length=20)),
                ('Username', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
    ]
