# Generated by Django 4.1.2 on 2022-11-12 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher_tb',
            old_name='Addres',
            new_name='Address',
        ),
    ]
