# Generated by Django 4.1.2 on 2022-12-16 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0002_rename_addres_teacher_tb_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_tb',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
