# Generated by Django 4.1.2 on 2022-12-21 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0003_teacher_tb_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_tb',
            name='File',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
