# Generated by Django 4.1.2 on 2022-12-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0005_activity_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyActivity_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Events', models.CharField(max_length=20)),
                ('Program', models.CharField(max_length=20)),
                ('Time', models.CharField(max_length=20)),
                ('Date', models.CharField(max_length=20)),
            ],
        ),
    ]
