# Generated by Django 4.1.2 on 2022-12-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0006_dailyactivity_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_name', models.CharField(max_length=20)),
                ('Description', models.CharField(max_length=20)),
                ('Venue', models.CharField(max_length=20)),
                ('Date', models.CharField(max_length=20)),
                ('Food', models.CharField(max_length=20)),
            ],
        ),
    ]
