# Generated by Django 4.1.2 on 2022-12-27 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0007_event_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=20)),
            ],
        ),
    ]
