# Generated by Django 4.1.2 on 2022-12-27 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Parent', '0006_parent_tb_file'),
        ('Teacher', '0009_present_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absent_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Attendenceid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Teacher.attendence_tb')),
                ('Studentid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Parent.student_tb')),
            ],
        ),
    ]
