# Generated by Django 4.1.2 on 2022-12-27 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0010_absent_tb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyactivity_tb',
            old_name='Events',
            new_name='Food',
        ),
        migrations.RenameField(
            model_name='dailyactivity_tb',
            old_name='Program',
            new_name='Games',
        ),
        migrations.RenameField(
            model_name='dailyactivity_tb',
            old_name='Time',
            new_name='SleepingTime',
        ),
        migrations.AddField(
            model_name='dailyactivity_tb',
            name='Activity',
            field=models.CharField(default=1, max_length=20),
        ),
    ]
