# Generated by Django 4.1.2 on 2023-01-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0011_rename_events_dailyactivity_tb_food_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mother_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mother_name', models.CharField(max_length=20)),
                ('Details', models.CharField(max_length=50)),
                ('Phoneno', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=20)),
            ],
        ),
    ]
