# Generated by Django 4.1.5 on 2023-02-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0012_mother_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Gender', models.CharField(default='abc', max_length=20)),
                ('Age', models.CharField(max_length=20)),
                ('Image', models.FileField(max_length=20, upload_to='')),
                ('FatherName', models.CharField(max_length=20)),
                ('MotherName', models.CharField(max_length=20)),
                ('Phoneno', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='mother_tb',
            name='Address',
            field=models.CharField(max_length=30),
        ),
    ]
