# Generated by Django 4.1.2 on 2023-02-03 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0014_alter_absent_tb_studentid_alter_present_tb_studentid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity_tb',
            old_name='ActionSong',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='activity_tb',
            old_name='Drawing',
            new_name='Item',
        ),
        migrations.RemoveField(
            model_name='activity_tb',
            name='SleepingTime',
        ),
        migrations.RemoveField(
            model_name='activity_tb',
            name='Studying',
        ),
        migrations.AddField(
            model_name='activity_tb',
            name='File',
            field=models.FileField(default=1, max_length=20, upload_to=''),
        ),
    ]
