# Generated by Django 4.1.2 on 2023-02-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0015_rename_actionsong_activity_tb_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodShedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Snack', models.CharField(max_length=20)),
                ('Lunch', models.CharField(max_length=20)),
                ('Eveningsnack', models.CharField(max_length=20)),
            ],
        ),
    ]
