# Generated by Django 4.1.5 on 2023-02-03 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0016_foodshedule'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoodShedule',
            new_name='FoodShedule_tb',
        ),
    ]
