# Generated by Django 4.1.2 on 2023-02-10 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0019_rename_vaccination_vaccination_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccination_tb',
            name='studentid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Teacher.student_tb'),
        ),
    ]
