# Generated by Django 4.1.2 on 2023-02-10 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Parent', '0010_student_tb'),
        ('Teacher', '0020_vaccination_tb_studentid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccination_tb',
            name='studentid',
        ),
        migrations.AlterField(
            model_name='absent_tb',
            name='Studentid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Parent.student_tb'),
        ),
        migrations.AlterField(
            model_name='present_tb',
            name='Studentid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Parent.student_tb'),
        ),
        migrations.DeleteModel(
            name='Student_tb',
        ),
    ]
