# Generated by Django 4.1.2 on 2023-02-11 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0021_remove_vaccination_tb_studentid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='vaccination_tb',
        ),
    ]
