# Generated by Django 4.1.2 on 2023-02-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0022_delete_vaccination_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrowthDetails_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Date_of_birth', models.CharField(max_length=20)),
                ('Birth_reg_no', models.CharField(max_length=20)),
                ('Fathername', models.CharField(max_length=20)),
                ('Mothername', models.CharField(max_length=20)),
                ('Family_survey_regno', models.CharField(max_length=20)),
            ],
        ),
    ]
