# Generated by Django 4.1.2 on 2023-02-18 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0023_growthdetails_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='mother_tb',
            name='Height',
            field=models.CharField(default='abc', max_length=30),
        ),
        migrations.AddField(
            model_name='mother_tb',
            name='Hemoglobin',
            field=models.CharField(default='abc', max_length=30),
        ),
        migrations.AddField(
            model_name='mother_tb',
            name='Nutritionsupplements',
            field=models.CharField(default='abc', max_length=30),
        ),
        migrations.AddField(
            model_name='mother_tb',
            name='Weight',
            field=models.CharField(default='abc', max_length=30),
        ),
    ]
