# Generated by Django 4.1.2 on 2023-02-18 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0024_mother_tb_height_mother_tb_hemoglobin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mother_tb',
            name='Nutritionsupplements',
        ),
    ]
