# Generated by Django 4.1.2 on 2023-02-18 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0025_remove_mother_tb_nutritionsupplements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutritions_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
            ],
        ),
    ]
