# Generated by Django 4.1.2 on 2023-02-18 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0026_nutritions_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='mother_tb',
            name='Nutritions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Teacher.nutritions_tb'),
        ),
    ]
