# Generated by Django 4.1.2 on 2023-02-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0028_mother_tb_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='THR_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item', models.CharField(max_length=30)),
                ('Quantity', models.CharField(max_length=30)),
            ],
        ),
    ]
