# Generated by Django 4.1.2 on 2023-03-04 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0031_lactatingwoman_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='lactatingwoman_tb',
            name='Thr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Teacher.thr_tb'),
        ),
    ]
