# Generated by Django 4.1.2 on 2023-03-18 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0032_lactatingwoman_tb_thr'),
    ]

    operations = [
        migrations.AddField(
            model_name='absent_tb',
            name='Date',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='present_tb',
            name='Date',
            field=models.CharField(default='', max_length=20),
        ),
    ]
