# Generated by Django 4.1.2 on 2023-03-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0033_absent_tb_date_present_tb_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity_tb',
            name='Date',
            field=models.CharField(default=1, max_length=20),
        ),
    ]
