# Generated by Django 4.1.5 on 2023-04-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0035_foodshedule_tb_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_tb',
            name='confirmpassword',
            field=models.CharField(default=1, max_length=20),
        ),
    ]
