# Generated by Django 4.1.2 on 2022-12-21 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Parent', '0002_parent_tb_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Age', models.CharField(max_length=20)),
                ('Image', models.FileField(max_length=20, upload_to='')),
                ('Phoneno', models.CharField(max_length=20)),
                ('Parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Parent.parent_tb')),
            ],
        ),
    ]
