# Generated by Django 4.1.2 on 2022-12-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parent', '0003_student_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_tb',
            name='Gender',
            field=models.CharField(default='abc', max_length=20),
        ),
    ]
