# Generated by Django 4.1.2 on 2022-12-26 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Parent', '0004_student_tb_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_tb',
            name='Parent',
        ),
        migrations.AddField(
            model_name='student_tb',
            name='Parentid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Parent.parent_tb'),
        ),
    ]
