# Generated by Django 4.1.2 on 2022-12-27 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parent', '0005_remove_student_tb_parent_student_tb_parentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent_tb',
            name='File',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
