# Generated by Django 4.1.2 on 2022-12-28 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parent', '0006_parent_tb_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='sponsership_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SponserName', models.CharField(max_length=20)),
                ('Job', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=20)),
                ('SponserItem', models.CharField(max_length=20)),
            ],
        ),
    ]
