# Generated by Django 4.1.5 on 2023-02-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0014_alter_absent_tb_studentid_alter_present_tb_studentid'),
        ('Parent', '0007_sponsership_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent_tb',
            name='Address',
            field=models.CharField(default=1, max_length=20),
        ),
        migrations.DeleteModel(
            name='Student_tb',
        ),
    ]
