# Generated by Django 4.1.2 on 2023-02-10 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parent', '0009_alter_parent_tb_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Gender', models.CharField(default='abc', max_length=20)),
                ('Age', models.CharField(max_length=20)),
                ('Image', models.FileField(max_length=20, upload_to='')),
                ('FatherName', models.CharField(max_length=20)),
                ('MotherName', models.CharField(max_length=20)),
                ('Phoneno', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=20)),
            ],
        ),
    ]
