# Generated by Django 4.1.2 on 2023-02-10 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Parent', '0010_student_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_tb',
            name='Parentid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Parent.parent_tb'),
        ),
    ]
