# Generated by Django 4.1.2 on 2023-02-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parent', '0012_vaccination_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_tb',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
