# Generated by Django 4.1.5 on 2023-04-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parent', '0013_student_tb_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent_tb',
            name='confirmpassword',
            field=models.CharField(default=1, max_length=20),
        ),
    ]
