# Generated by Django 4.1.5 on 2023-10-26 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_register'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='login_tb',
        ),
        migrations.RenameModel(
            old_name='register',
            new_name='register_tb',
        ),
    ]
