# Generated by Django 4.1.5 on 2023-10-27 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_login_login_tb_rename_register_register_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='form_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Dob', models.CharField(max_length=20)),
                ('Age', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=20)),
                ('Phonenumber', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=20)),
                ('Department', models.CharField(max_length=20)),
                ('Courses', models.CharField(max_length=20)),
                ('Materials', models.CharField(max_length=20)),
            ],
        ),
    ]
